### ISSUE TITLE
Clone Item without attachments retains attachment UUIDs in XML

### ISSUE THREAD

**Issue by timrattle** [openequella/openEQUELLA#1093]
1.  Clone an item without attachments (note the UUIDs of attachments)
2.  Look at the XML of the newly cloned attachment and you'll see the UUIDs of the attachments from the original item. 

This has been replicated in 2018.2 r28.

**Comment by carl-edalex** [comment]
Another client has also reported this, and it's a bit more complicated.  Here are two scenarios:

1.  They clone without attachments and they add new attachments (first page).  Then they go to the second page and sometimes go back to the first page.  The attachment control does not show the attachments that they've just uploaded.

2.  They clone without attachments and add new ones.  They complete the subsequent pages and save.  No attachments show up on the item summary.  XML shows the old attachment UUIDs but not the new ones, but the attachments are still there.

What I tried to do was put some scripting on the first page that if it is a clone (I have scripting that does this), it deletes the xpath (and therefore, metadata values) registered to the attachment control, then iterates across any attachments, assigning the actual UUIDs (if they exist).  This function only runs once (using another metadata value) - so if it was cloned without attachments, it removes the legacy UUIDs; and if they add new ones, the script doesn't run (because it ran on on contribution).  This works most of the time ... but because of the display bug:  https://github.com/apereo/openEQUELLA/issues/614, doesn't seem to be consistent.  Even with this, sometimes the old attachment UUIDs are still there and the new ones aren't, meaning that no attachments show on the item summary.

So finally what I've had do do is implement a save script that re-registers all attachment uuids to their proper xpath.  But this is a crude and blunt instrument because it doesn't take into consideration unzipped archives where you might only want to display one of the contained files.

This has become urgent.

Thanks,

Carl

**Comment by abidingotter** [comment]
This is actually not as simple as it might sound.  In fact, probably not even do-able in a clean way.

An attachment is not “tied” to an xpath.  There is no way of determining where the attachment UUIDs might have been stored in the XML.  In fact, an attachment UUID might legitmately appear in multiple XML nodes.

The only way that this could be done is to look at every single node in the XML and compare it with every attachment.  If there is a match, then remove it.  (And this assumes that you didn’t add the UUID to the XML yourself for historical records)

Having said that, it shouldn’t not show new attachments if you have extraneous attachment UUIDs in the XML.  So my first action will be to reproduce that issue and resolve it.

**Comment by abidingotter** [comment]
P.s. this would have been happening since 6.x (or earlier?) whenever the multiple item summary attachments sections feature was implemented

**Comment by abidingotter** [comment]
Could not reproduce the issue with the attachments going missing, either by going back and forwards between pages, or just continuing on and completing the wizard.  Will need a minimal basic schema and collection export that reproduces the issue to diagnose further.

**Comment by abidingotter** [comment]
@carl-edalex Hi Carl, could you provide exports for this?  I cannot reproduce any issue with missing attachments.  Note that removal of the UUIDs from the XML itself is probably not possible.
