### ISSUE TITLE
Follow up with Apereo regarding TinyMCE

### ISSUE THREAD

**Issue by SammyIsConfused** [openequella/openEQUELLA#1104]
Send out a note to Apereo that we are planning to remove the embedded TinyMCE, then use the node.js version.

**Comment by cbeach47** [comment]
Note sent out to Apereo.

**Comment by cbeach47** [comment]
-  It's fairly clear that the embedded version is not OK, and needs to be removed and replaced with the TinyMCE version in node.js.  
- Since TinyMCE is LGPL, but it's pulled in as a dependency and no TinyMCE authored code is stored in the openEQUELLA repos, we should be safe.
- However, I believe building a binary release of openEQUELLA that bundles TinyMCE from node.js and then putting that release on the github releases page or uploading as a docker image to the Apereo org's github account would not be appropriate.

**Comment by cbeach47** [comment]
Opened #1219 and #1220 .

**Comment by ChristianMurphy** [comment]
@cbeach47 with #1219 and #1220 being tracked does anything remain for this item? Can it be closed?
