### ISSUE TITLE
PDFs not thumbed correctly with latest ImageMagick

### ISSUE THREAD

**Issue by smclaughlin520** [openequella/openEQUELLA#142]
Confirmed in 6.4-QA1, and based on the code, looks to affect 6.2-QA1 and 6.3-QA4.
 
 Using the latest ImageMagick (6.9.3-Q16) and the attached pdf, the background is black instead of the expected white. Switching to ImageMagick 6.9.1-Q16 and re-contributing the pdf generates the thumbnail as expected.
 
Issue Converted from original Equella JIRA

**Comment by phette23** [comment]
We're still experiencing this (6.5 stable). If anyone runs into it, this is something from an old support email I received:

---

My unconfirmed suspicion is that these pdf files were built using layers. Most programs render the bottom layer as white, then stakck subsequent layers on top of that of course. I formerly worked in graphic design, and often saw layered pdf files render black if placed in another file (like illustrator, indesign, etc) as an image without being flattened. It would seem the default settings for IM do not flatten the pdf while thumbing, and since jpgs don't support transparency, it is defaulting to black for the background. I can't imagine why the IM coders used that for the default.

I can tell you, though, that another client found the below workaround. I can't guarantee it will work or that it won't cause any problems, so you can try this at your own risk. They've reported no issues with it. It just calls the flatten function for pdf files only, which lends credence to my theory of the root cause.

They have placed a bash script in the path where EQUELLA thinks ImageMagick is located '/usr/local/bin/convert' with the contents of:

```sh
if [[ $@ == ".pdf" ]] ;
then
/usr/bin/convert -flatten $@
else
/usr/bin/convert
$@
fi
```

---

I've not tested that but we're getting tired of these black thumbnails for PDFs so I may try it out soon and report back here.

**Comment by cbeach47** [comment]
Thanks @phette23 - The hooks for oE > IM need updating.  I've created the `Thumbnails/Previews` label to gather the issues. 

With the `-flatten` flag, we should consider where we'd want to inject that - install, institution, collection, or scripting level.

**Comment by phette23** [comment]
A note for people who want to try this: that script above is definitely not correct. It should probably be something like this:

```sh
if [[ $@ == *".pdf"* ]] ;
then
    /path/to/convert -flatten "$@"
else
    /path/to/convert "$@"
fi
```

but I couldn't get that work either, I get a bunch of "No such file or directory" errors in our logs probably due to some sort of problem with spaces in filenames and quoting command parameters.

**Comment by phette23** [comment]
This is still a major issue for us and should not be closed. I appreciate trying to manage issues but just because there hasn't been commentary or progress on something doesn't mean it's been resolved. We've had to stop showing thumbnails for PDFs in most collections, showing a generic icon, because they're all coming out blackened.
