### ISSUE TITLE
Customize header and footer

### ISSUE THREAD

**Issue by aponsl** [openequella/openEQUELLA#1517]
We are currently using openEQUELLA version 2019.2, and are working with Next Education Services on a government project. 

We need to use the new UI template which offers responsive design.  

It is not possible to add custom link or small images in the header / footer by changing the CSS stylesheet.

We believe that this functionality would be helpful for other openEQUELLA users.

Can openEQUELLA developers update this??”

**Comment by garnetberrry** [comment]
Garnet here from Next Education Services, to share that we are collaborating with @aponsl. 

We have shared current status of functionality based on the different openEQUELLA versions.  If anyone would like more context or information please let me know.

Thanks
Garnet

**Comment by cathfitz** [comment]
@aponsl @garnetberrry Could you please clarify your requirements with some further information and possibly screen shots of what you need to achieve? Thank you.

**Comment by garnetberrry** [comment]
Hi @cathfitz 

We would like to share a mock up showing a Header and Footer within responsive openEQUELLA UI 2019.2 as desired by Government end user.  This is important as the external links represent things like Legal and GDPR.

**Requirements:**
Responsive Header and Footer containing linkable pictures (e.g. logos) and/or linkable text

**Mock up design:**
Header, as you can see in the image, there are 2 logos and some text
Footer, there are 4/5 logos which are linkable along with some linkable text
*if possible enabling JAVA SCRIPT (or similar) in the Header / Footer would be favourable so that admin can create own link behaviour. 
Example, like to other authentication pages or system triggers.

**Image:**
![image001](https://user-images.githubusercontent.com/48282586/77299321-2fe37300-6ce4-11ea-8717-36a4ae817c08.png)
