### ISSUE TITLE
Make sharing ACLs restricted searches more intuitive

### ISSUE THREAD

**Issue by cbeach47** [openequella/openEQUELLA#1726]
**Is your feature request related to a problem? Please describe.**
When sharing a search that the user should log into oEQ first (ie a ACLs restricted advanced search), the user first has to add `logon.do?page=` into the URL, otherwise the search is performed, but unexpected results are returned (such as an empty list).

**Describe the solution you'd like**
Have a checkbox under the 'share search via URL' that will add the `logon.do?page=` for you, and encode the page parameter value so the redirect happens properly.

**Comment by cathfitz** [comment]
@cbeach47 Could you please step through an example or attach a video so we can see exactly what the problem might be? There's not quite enough info for us to reproduce. Thanks

**Comment by phette23** [comment]
Minute-long video: https://youtu.be/72RCphB9ykg

Steps to recreate:
- login and perform a search in a collection or power search that _is not usable by everyone_
- use the share feature to copy the `searching.do...` link
- sign out, paste the copied link in URL bar
- user is not prompted to sign in, a malformed version of the shared search is performed (often with no results or, worse, different results), the user has no indication that they need to sign in or that they're seeing different results than what was intended

I would amend @cbeach47's suggestion to not include a checkbox but simply automatically send any shared search that requires authentication (doesn't have "Everyone" in the appropriate ACL) URL through logon.do, since I don't see the use case in sending a malfunctioning search to someone. If that's not possible for some reason, the search interface should at least show an indication that the search being performed is likely the wrong one due to the ignored `in` query string parameter.

**Comment by cbeach47** [comment]
thanks for the details @phette23 .  Mostly makes sense to drop the checkbox to add the `logon.do`, however since it'd then encode the URL, it wouldn't be straight forward / simple effort to turn the URL into a guest viewable one, so having an alternative might be useful (maybe keep the checkbox, but have the default be to add `logon.do`.  Not sure if checking the ACLs would be unambiguous to always make the correct choice on which URL form to display.

**Comment by abidingotter** [comment]
I think the best solution is to throw an AccessDeniedException if it can't find the collection specified in the URL.  
I quickly hacked this up in SearchQuerySection:447

```
final Collection<ItemDefinition> collections =
		collectionService.getMatchingSearchableUuid(Lists.newArrayList(selCollection.getUuid()));
			if (collections.size() == 0)
			{
				throw new AccessDeniedException("Bad luck");
			}
```

Alternatively, you could forward to logon page, however the user may not even have a login (but can normally access the search page) so it might be confusing to them:
```
final Collection<ItemDefinition> collections =
		collectionService.getMatchingSearchableUuid(Lists.newArrayList(selCollection.getUuid()));
			if (collections.size() == 0)
			{
				InfoBookmark bookmark = rootSearchSection.getPermanentUrl(info);
				LogonSection.forwardToLogon(info, institutionService.removeInstitution(bookmark.getHref()),
					LogonSection.STANDARD_LOGON_PATH);
			}
```

Note that you would need to do similar checks for advanced searches and dynamic collections.
Disclaimer:  I'm not advocating that either of those code snippets be used in the final product :)
