### ISSUE TITLE
SCORM import - repeater fields missing

### ISSUE THREAD

**Issue by NextEdServices** [openequella/openEQUELLA#1786]
There is a problem with SCORM zip file uploads and repeater fields.

Problem:
when uploading SCORM files containing repeating values, these repeated values are not imported into openEQUELLA.

We have raised this issue with Edalex previously, please see ticket number 101337 for more details and example package to replicate (SCORM package, metadata schema, collection export)

**Comment by mrblippy** [comment]
Hi @NextEdServices, is it possible for you to attach a screen recording demonstrating the issue? 
Or some more detailed steps to reproduce?

**Comment by NextEdServices** [comment]
Hi, screenrecording, SCORM file and collection by request (cannot upload here)

Steps:
1) contribute / upload SCORM zip file containing repeating metadata values into collection that has referring repeater fields marked as mandatory
2) some of the mandatory repeater fields are not imported correctly
3) remove mandatory setting in the wizard, contribute / upload same SCORM course - and the SCORM metadata values are imported.


Wizard setting with mandatory fields:
![image](https://user-images.githubusercontent.com/50982397/92645329-f976d000-f2e4-11ea-83a9-29bd3cddc803.png)

After Uploading SCORM Course no Rol entry:
![image](https://user-images.githubusercontent.com/50982397/92645481-3216a980-f2e5-11ea-8724-bcffd91db5bf.png)

Wizard setting without mandatory fields:
![image](https://user-images.githubusercontent.com/50982397/92645586-5a060d00-f2e5-11ea-9739-4dd401f1428c.png)

After Uploading SCORM Course ok:
![image](https://user-images.githubusercontent.com/50982397/92645644-6db17380-f2e5-11ea-868b-95719a83138b.png)

(Further: Please note there is different behaviour when uploading SCORM courses with the contribution upload link or with clicking in the file upload field. The latter seem not to import repeater values either.)

**Comment by NextEdServices** [comment]
@mrblippy I have emailed you a direct link as I had difficulties uploading (sensitive) material. Let me know if you have any issues or questions.

**Comment by edalex-ian** [comment]
We currently have this on our list to look at, so re-opening.

**Comment by SammyIsConfused** [comment]
@NextEdServices I was attempting to diagnose and fix this problem in-code, and I discovered that it is not actually a bug, rather a collection configuration issue.

So in the your collection you have the repeater in question set up like this: 

![image](https://user-images.githubusercontent.com/24543345/108805415-103f8380-75f4-11eb-8d4f-9d0488b2667a.png)

You also have IMS metadata mapping set up for these fields, so openEQUELLA should create repeater instances for each element that matches this xpath, but it doesn’t. 

Now, the problem itself is a little unintuitive - the field labelled "Minimum number of repeats" is set to 1. For some reason this disables metadata mapping to repeaters - it seems to be that the minimum count is for manually inputting data into repeaters fields rather than mapping them from metadata. 

If you set that field to 0, and save the collection, data should map properly. I have tested this with your collection and SCORM package locally on my machine. I also during testing edited the imslrm.xml to contain multiple different values of lom/lifeCycle/contribute, to make sure that openEQUELLA would add and map repeaters for each one.

[testing video clip](https://github.com/openequella/openEQUELLA/files/6026941/Peek.2021-02-23.15-57.zip)
I have attached a short clip of me doing the following testing steps in order:

1. In the Administration Console, open the Buenas prácticas collection in the editor and find the Contribuciones repeater. Set the minimum number of repeats to 0 and hit Save.

2. Open a contribution using the Buenas prácticas collection and add the SCORM package, as it is without changes.

3. Go to the Obligatorios page and scroll down to the Contribuciones repeater.

4. Note that the Rol field is populated in one repeater.

5. Repeat step 2 and 3, this time using a modified version of the client’s SCORM package that contains another two instances of lom/lifeCycle/contribute in the imslrm.xml to prove that it is mapping properly. In each additional lom/lifeCycle/contribute node, the Rol and the Nombre values are edited.

6. Note that the Rol field is populated for 3 repeaters.
