### ISSUE TITLE
React components get rendered twice

### ISSUE THREAD

**Issue by PenghaiZhang** [openequella/openEQUELLA#2262]
**Describe the bug**
If open a `tsx` page from a legacy page, the React component in this `tsx` page will get mounted twice, which resulted in React state update warings and duplicated API calls. This issue does not happen if users open a `tsx` page from another `tsx` page.

**To Reproduce**

1. With New UI on, open a legacy page such as `contribute`;
2. Open any `tsx` page such as `Search` or `Settings` ;
3. Observe the Browser's Console and Network tabs.

Please note that you WON''T see the warning if you open  `Settings`  because this page has special code to prevent this warning.  
Please search `cleanupTriggered` to get more details.

**Expected behavior**
The React component should be mounted once.

**Screenshots**
![image](https://user-images.githubusercontent.com/47203811/92839233-10bbd780-f423-11ea-8df5-f0e052b0e632.png)

![image](https://user-images.githubusercontent.com/47203811/92839291-1f09f380-f423-11ea-8e72-baa1acc7d242.png)

**Stacktrace**
If applicable, a stacktrace to help explain your problem.

**Platform:**

- OpenEquella Version: 2020.2
- OS: Ubuntu 18.04
- Browser Chrome

**Additional context**

**Comment by PenghaiZhang** [comment]
The last `useEffect` in `LegacyPage` may cause this problem.

**Comment by edalex-ian** [comment]
Did you say you already had a fix for this @PenghaiZhang ?

**Comment by PenghaiZhang** [comment]
> Did you say you already had a fix for this @PenghaiZhang ?

Not yet. I worked out why this issues happens but I am not confident in my fix without enough knowledge of `full screen mode` in oEQ.

**Comment by edalex-ian** [comment]
Okay, so we've been having a bit more fun with this one and we really need to get it sorted - but alas, with the release about to go out we have to just capture our findings. So here we go.

First, the effect which @PenghaiZhang references above is found on [line 150 of LegacyPage.tsx](https://github.com/openequella/openEQUELLA/blob/215f54953712e6a052d25916bd9f3516c5dcf843/Source/Plugins/Core/com.equella.core/js/tsrc/mainui/LegacyPage.tsx#L150) and looks like:

```typescript
    React.useEffect(
      () => () =>
        legacyContent.setLegacyContentProps((p) => ({ ...p, enabled: false })),
      []
    );
```

Another bit worth understanding is the relevant part of the component tree for two cases of interest.

First, component tree if I'm viewing some Legacy UI pages looks like:

- `IndexPage`
  - `LegacyContent`
    - router bits
      - `LegacyPage`

And then when viewing the New Search page - or indeed, other New UI pages:

- `IndexPage`
  - `LegacyContent`
    - router bits
      - `SearchPage`

Okay, so now with that pre-requisite knowledge let's got back and review that `useEffect` - which is a little interesting.

It's an effect which has no substance other than to setup a clean-up function - kind of mimicking `componentWillUnmount`. What's more interesting, is that it's calling a passed in state set function (`setLegacyContentProps()`) from further up the tree.

And when I say further up the tree, I mean almost at the top in [`IndexPage` on line 76](https://github.com/openequella/openEQUELLA/blob/215f54953712e6a052d25916bd9f3516c5dcf843/Source/Plugins/Core/com.equella.core/js/tsrc/mainui/IndexPage.tsx#L76).

So if a user is viewing a Legacy UI page (e.g. Dashboard) then goes to the `SearchPage` the rendering of `SearchPage` commences. However now the clean-up is triggered which performs a state change on `IndexPage`. This in turn now triggers a re-render of `IndexPage` and then also `LegacyContent` down into `SearchPage` - and hence, we end up with a double render.

What is the point of this?

Well that's lost in time, however if you comment out that `useEffect` all still works. But... when going back to look at a Legacy UI page there will first be a slight flicker of the last legacy page you were on before it shows the content of the new page. As the content for `LegacyPage` is a prop which is state managed by an effect from way back up in `IndexPage` or `LegacyContent`.

What to do?

Well, that's a bit of a tricky one. But it feels as though rather than managing the content in state way up the tree it should really be owned by the `LegacyPage` component. And that way, it would only live while the component lives and we wouldn't need any of this reaching around for clean-up.

However, without understanding the full reason for while the design is as is. So further investigations are required.
