### ISSUE TITLE
Improved image scaling when setting a theme logo

### ISSUE THREAD

**Issue by edalex-ian** [openequella/openEQUELLA#2478]
**Is your feature request related to a problem? Please describe.**

In the new UI Theme editor, setting a logo always scales the logo to a fixed size of 230px by 32px with no regard to original images aspect ratio or otherwise.

**Describe the solution you'd like**

To improve flexibility, you should be able to upload any sized image, and it's aspect ratio is kept after scaling.

**Comment by edalex-ian** [comment]
Heya @SammyIsConfused 

Could you test this one please?

**Comment by SammyIsConfused** [comment]
Looks good to me. Aspect ratio is maintained, and width is confined to 230 pixels. I looked at some edge cases - eg a file that was 230 x 3000, an animated gif, a broken file. All were handled fine, where possible converted in to a crisp PNG logo file. Obviously the animated gif just took the first frame, but that frame was high quality and the correct ratio. The super long files with width 230 were of high quality and displayed in full. As a sanity check, I renamed a text file to a PNG and uploaded that, and it was caught by the error boundary. 

Files that are too wide can still be used but the conversion step adds some aliasing when re scaling which is to be expected. 

I'd say this issue is complete, @edalex-ian . :+1:
