### ISSUE TITLE
Failed to login into the 6.4VanillaReferenceInstitution example

### ISSUE THREAD

**Issue by tsnouidui** [openequella/openEQUELLA#2773]
**Describe the bug**
I have successfully installed EQUELLA locally. 
I have then imported the 6.4VanillaReferenceInstitution. However I am also failing to login.
What is the correct user name to use?
Currently I have tried with admin, administrator, TLE_ADMINISTRATOR with no luck

**Comment by edalex-ian** [comment]
Heya @tsnouidui 

The username to login with is `TLE_ADMINISTRATOR`, and the password will be whatever you set it to during import. However, if you left that field blank it will simply use what was in the institution at time of export. So... please make sure you specify a value.

**Comment by tsnouidui** [comment]
I have used those credentials. However, I am only getting the following message:
"Sorry, the details you supplied were invalid."
Is there anything that I need to configure? A database or anything?

**Comment by edalex-ian** [comment]
Okay so looking at this screen after importing the Vanilla institution

![image](https://user-images.githubusercontent.com/43919233/109609160-13e88280-7b7f-11eb-97ef-c86746c5ec26.png)

There are two key things to make sure you edit:

1. Make sure the 'Institution URL' correctly matches where you plan to run it - including be sure to use the correct hostname and the correct protocol specification (http vs https); and
2. Ensure that you specify an 'Admin password' you're happy with.

If these are definitely all correct, then a screenshot would definitely help of both the above screen after you've entered all the values and the failed login.

**Comment by tsnouidui** [comment]
I have managed to go up to here.

![image](https://user-images.githubusercontent.com/3789840/109610121-5e490f80-7b3d-11eb-8fe9-194a118955e3.png)

Please note that I am running equella on my local machine for testing purposes first. Hence the URL is 

http://localhost/EQUELLA/uaut/

I can even edit the password but then when I try to login 

![image](https://user-images.githubusercontent.com/3789840/109610341-ac5e1300-7b3d-11eb-8a8e-46b475e29e79.png)

With TLE_ADMINISTRATOR as user and with my selected password I get 

![image](https://user-images.githubusercontent.com/3789840/109610416-c7308780-7b3d-11eb-81e2-e7283a15fd28.png)


I do see a folder name `uaut` in my local machine. It is under `\filestore\Institutions` of the EQUELLA' s local installation folder.

It there any other way to get/see those credentials?

**Comment by edalex-ian** [comment]
I'll have a bit more of a look tomorrow - but one thing that is jumping out at me is having the path within a path (i.e. EQUELLA/uaut). I've not personally tried that before - normally just one level, or at the hostname level. If you could try reducing that and let me know it could be useful.

**Comment by tsnouidui** [comment]
I have changed to `http://localhost/uaut/` with no success. I am still getting the same error message. It doesn't seem to look up the credentials somehow.

**Comment by edalex-ian** [comment]
hmmm, well in that case I recommend we have a look in the logs. As per the [quick start doco](https://openequella.github.io/gettingstarted/InstallingEquella.html) they can be found at:

    {install_location}/logs/resource-centre/{current_date}/application.{X.}html

Have a look through there for any errors, or if you happy to, attach them to this issue.

**Comment by tsnouidui** [comment]
any feedback on this? I am about to give up on this and go back to dspace :-)?

**Comment by tsnouidui** [comment]
I have managed to install and import the reference institution for version 2019 on Ubuntu. Version 2019 was exhibiting the same problem on Windows. Hence I suspect that there is a fundamental problem with Windows.

**Comment by edalex-ian** [comment]
Thank you for yet again persisting @tsnouidui . That is interesting that you should have such issues on Windows, but great to hear you've got it all running happily on Ubuntu.

But did you say you're now running a 2019.x version?

**Comment by SammyIsConfused** [comment]
Hi,
So I've just gone through and testing installation of 2020.2 on Windows 10 and everything went smoothly. I was able to install the reference institution and log into it. Here are the versions I used.

- Windows 10 Enterprise in a VirtualBox VM
- jdk 8u291-b09 downloaded from Oracle 
- 2020.2 from the Releases Page
- PostgreSQL 13.2-1 Windows
- Copy of VanillaReferenceInstitution from openequella.github.io
- ImageMagick 7.0.11-2

    
Two things: 
- In your screenshot you have a filestore limit of 200MB which is quite small. It shouldn't make any difference, but if you set this to 0 does that change your situation at all? 
- Make sure to remember to set a password when importing a new institution. If you don't set one then it keeps the pre-existing value as the TLE_ADMINISTRATOR password. Since this value is hashed, its impossible to find out what this is unless you know it and can log in. So if you overwrite it you should have no problems.

**Comment by SammyIsConfused** [comment]
I had another thought about this as well - so when I was initially installing I briefly hit a minor snag. Once I'd gone through the installation wizard I went to install the openEQUELLA Windows Service so I could boot up the server, and it went like this: 
```
> equellaserver install
Installing the EQUELLA service
```
I assumed that it had worked properly, so I went to start the server.
```
> equellaserver start
Please install the EQUELLA service using the "install" command
```
which is what I had just done but clearly it didn't work properly. 
Turned out this was because I needed to run Command Prompt as an Administrator. Once I did that, installing the service and booting the server went as normal.

**Comment by tsnouidui** [comment]
> I had another thought about this as well - so when I was initially installing I briefly hit a minor snag. Once I'd gone through the installation wizard I went to install the openEQUELLA Windows Service so I could boot up the server, and it went like this:
> 
> ```
> > equellaserver install
> Installing the EQUELLA service
> ```
> 
> I assumed that it had worked properly, so I went to start the server.
> 
> ```
> > equellaserver start
> Please install the EQUELLA service using the "install" command
> ```
> 
> which is what I had just done but clearly it didn't work properly.
> Turned out this was because I needed to run Command Prompt as an Administrator. Once I did that, installing the service and booting the server went as normal.

Thanks for the feedback. I figured that out running the Command Prompt as an administrator as well.

**Comment by tsnouidui** [comment]
> Hi,
> So I've just gone through and tested installation of 2020.2 on Windows 10 and everything went smoothly. I was able to install the reference institution and log into it. Here are the versions I used.
> 
> * Windows 10 Enterprise in a VirtualBox VM
> * jdk 8u291-b09 downloaded from Oracle
> * 2020.2 from the Releases Page
> * PostgreSQL 13.2-1 Windows
> * Copy of VanillaReferenceInstitution from openequella.github.io
> * ImageMagick 7.0.11-2
> 
> Two things:
> 
> * In your screenshot you have a filestore limit of 200MB which is quite small. It shouldn't make any difference, but if you set this to 0 does that change your situation at all?
> * Make sure to remember to set a password when importing a new institution. If you don't set one then it keeps the pre-existing value as the TLE_ADMINISTRATOR password. Since this value is hashed, its impossible to find out what this is unless you know it and can log in. So if you overwrite it you should have no problems.

Thanks a lot for the feedback.

I have changed the filestore size to 0.0 with no effect.

I have also made sure to change and use the TLE_ADMINISTRATOR password while importing the reference institution.

Now I found something interesting:

I can login using the TLE_ADMINISTRATOR account from the administration console but I can't do it from the web interface?? There seems to be a problem somewhere there

BTW: Is there a way to change the TLE_ADMINISTRATOR password from the administration console?

I wanted to reset it there and then see if that will have an impact on the web since I changed the password of the user `demosysadmin` from the console and was then able to login from the web

**Comment by tsnouidui** [comment]
> Thank you for yet again persisting @tsnouidui . That is interesting that you should have such issues on Windows, but great to hear you've got it all running happily on Ubuntu.
> 
> But did you say you're now running a 2019.x version?

I am able to run a 2020.x version on Ubuntu 18.04 as well.

**Comment by tsnouidui** [comment]
While going through the following google group posts, I came across this thread

https://groups.google.com/a/apereo.org/g/equella-users/c/BSgKIH_XbfA

and decided to use MS Edge on Windows to login to the institution account with the TLE_ADMINISTRATOR credentials.

Guess what, it worked!

So the problem seems to be related to the issue raised in the thread since I was using Chrome Version 88.0.4324.190 (Official Build) (64-bit) ??

**Comment by tsnouidui** [comment]
A quick question for my own understanding of the repo:

Suppose I have a collection that contains a number of journal articles posted by the `demosysadmin`
Now let say I would like all students of my university to have access to it?

1. What is the procedure for letting those users have access to the content to the collection?
2. Is it possible to set-up the repos so that users do not need to log in to see content authorized by the admin.
I have been trying to get this through the documentation but I am not totally sure about the procedure.

**Comment by SammyIsConfused** [comment]
Hi @tsnouidui - so there is no way to change the TLE_ADMINISTRATOR password from the admin console - that password is set in the institution manager when importing or editing an institution. 
If having problems in  one browser session but not another, that sort of sounds like a caching issue to me. have you tried doing a hard browser refresh (CTRL-SHIFT-R), closing and reopening the browser, or clearing your cache in the browser's F12 Developer settings?

> 1. What is the procedure for letting those users have access to the content to the collection?
I would go into the Admin Console and go to User Management. Click on Internal Roles, and create a new role for your students and add all of their accounts to it. 
Then, once that is saved come out of User Management and go into the Security Manager. Click on the dropdown arrow next to Collections, and find and select your collection. You will see a completely configurable list of permissions for this collection which you can grant or revoke to any role, group or user. Grant VIEW_ITEM to your Students role by double-clicking the "Who?" cell for your ACL. 

2. Is it possible to set-up the repos so that users do not need to log in to see content authorized by the admin.
Yes - so when setting the value for "Who?" in an ACL if you click the "Other" tab you will see an option for "Guest users". These are users that are not logged in. You can set any ACL to be granted or revoked for a guest user to determine what logged out users can do in your openEQUELLA. 

Hope this helps.

**Comment by tsnouidui** [comment]
> Hi @tsnouidui - so there is no way to change the TLE_ADMINISTRATOR password from the admin console - that password is set in the institution manager when importing or editing an institution.
> If having problems in one browser session but not another, that sort of sounds like a caching issue to me. have you tried doing a hard browser refresh (CTRL-SHIFT-R), closing and reopening the browser, or clearing your cache in the browser's F12 Developer settings?

@SammyIsConfused  I have cleared the cache with no luck. Did you try with Chrome? I can login with firefox and MS edge so only chrome is a problem.
> 
> > 1. What is the procedure for letting those users have access to the content to the collection?
> 
> I would go into the Admin Console and go to User Management. Click on Internal Roles, and create a new role for your students and add all of their accounts to it.
> Then, once that is saved come out of User Management and go into the Security Manager. Click on the dropdown arrow next to Collections, and find and select your collection. You will see a completely configurable list of permissions for this collection which you can grant or revoke to any role, group or user. Grant VIEW_ITEM to your Students role by double-clicking the "Who?" cell for your ACL.
> 
> > 1. Is it possible to set-up the repos so that users do not need to log in to see content authorized by the admin.
> 
> Yes - so when setting the value for "Who?" in an ACL if you click the "Other" tab you will see an option for "Guest users". These are users that are not logged in. You can set any ACL to be granted or revoked for a guest user to determine what logged out users can do in your openEQUELLA.
> 
> Hope this helps.

Thanks a lot. I will try and let you know

**Comment by tsnouidui** [comment]
A follow-up to my last question above

I have logged in as a `demosysadmin` and created an article under the eReserve Articles collection.
I have then used the admin console to change the permissions of `eReserve Articles` to be visible by Guest users.
However when I go to the main page of my institution (http://localhost/uaut/), I only see the logon page. How do I make that `eReserve Articles` accessible to public users.

**Comment by tsnouidui** [comment]
@SammyIsConfused Any feedback on the above question?

**Comment by SammyIsConfused** [comment]
Hi @tsnouidui - so I think you slightly misunderstood what that does. All it does is allows guest users to view the page, it doesn't change the log in screen to be eReserve Articles. 
If you go to the resource summary of your article, and grab the URL - you should be able to route to that URL whether you're logged in or not. It doesn't affect the login screen. Does that make sense? 
Also - I did try Chrome, yes. I'm unsure what's happening on your end.

**Comment by tsnouidui** [comment]
Oh, I see. Thanks. Maybe my version of Chrome is having some issues. Which version of Chrome are you using?
