### ISSUE TITLE
More Efficient Item Save 

### ISSUE THREAD

**Issue by cbeach47** [openequella/openEQUELLA#377]
Currently clicking Save in the item wizard brings up a publish/save draft/cancel dialog, creating an extra step for a portion of users.

This is a request to streamline the item save process.  Discussion around how to do so is welcome. 

There could just be buttons for cancel, save as draft, and save (disabled if required fields are missing, or if that's not possible have "save" cause the form error-checker to run and highlight missing fields).

**Comment by cbeach47** [comment]
Taking a look at this now - I'm thinking to use the following flow:

-  Have a flag in the Collection Definition Editor > Wizard screen (right below the 'Show page titles on Next/Prev buttons') labeled something to the effect 'Omit Item Save Dialog'
- In the wizard, if the flag above is set, the 'Save, Save and continue, Cancel' controls would be all buttons (styled like the current 'Save') and be 'Submit (if workflow and draft) / Save (all other cases), Save as draft, Cancel
- On clicking Submit / Save, if the wizard isn't complete, it'll present a message to the user and stay on the page.

**Comment by phette23** [comment]
I _love_ the idea to have save / save draft / cancel buttons instead of a dialog. It's worth noting that the save process for collections attached to a workflow is slightly different; instead of a green "publish" button users receive a green "submit for moderation" button with a text input for writing a message. I don't see much utility in the behavior differing, and sometimes a workflow doesn't even cause moderation so the button label is misleading, so the backwards-compatible solution of offering an "Omit item save dialog" setting should be sufficient if people do want workflow messages.

One please however: if this is going to be implemented as a setting, can there be some way to enable it globally or bulk update existing contribution wizards? We would want this setting enabled on every page in every contribution wizard, which means I'd have to go in and manually update over a hundred pages. Having a means of reducing that tedium would be appreciated.

**Comment by phette23** [comment]
This is still really important to us.
