### ISSUE TITLE
eqos-1814: Deleting a workflow node that is in use

### ISSUE THREAD

**Issue by emcgarrahan** [openequella/openEQUELLA#394]
Script scenario is as follows (please confirm this is the expected functionality):

- Should not be able to delete a workflow task that has been completed, if an item using the workflow is still in moderation.
- Should not be able to delete a workflow task if an item is currently on that task in moderation.

In both cases, I was able to delete the workflow task.

In the second case, because I deleted a workflow task while an item in moderation was on it, when refreshing the moderation progress screen, I receive the following message:

The URL you requested was:
http://equella-test.unicon.net/erin/items/a879e8ba-25df-4e1f-acee-9477be47e8e7.4a2d4ae0-cf73-44eb-aada-98c176b880d6/1/?is.summaryId=cmc&_taskState=1

Problem description:
Item not found a879e8ba-25df-4e1f-acee-9477be47e8e7.4a2d4ae0-cf73-44eb-aada-98c176b880d6/1

**Comment by doolse** [comment]
I'm not sure why that test script wasn't updated but the functionality was changed many years ago to allow you to delete a task no matter what and all that would happen would be that items that referenced the task would have their workflow reset to the start again (which i believe is shown as a warning when you delete the task?) 

As far as the "Item not found" goes, i believe that's happening because you were on the summary page in the context of the task which no longer exists. It should definitely be a nicer error message though I think.
