### ISSUE TITLE
Contribution - "Allow non-sequential navigation" checked should allow saving without visiting all pages first

### ISSUE THREAD

**Issue by doolse** [openequella/openEQUELLA#406]
When you have "Allow non-sequential page navigation for new resources" checked you should be able to save the item without needing to visit all the pages first. Currently it's showing asterisks next to pages which have mandatory fields and forcing you to fill them in.

**Comment by abidingotter** [comment]
I'm pretty sure you shouldn't be able to save without filling in mandatory
fields. Peng did a fix to make sure you can't.

On 14 Dec. 2017 3:47 pm, "Jolse Maginnis" <notifications@github.com> wrote:

When you have "Allow non-sequential page navigation for new resources"
checked you should be able to save the item without needing to visit all
the pages first. Currently it's showing asterisks next to pages which have
mandatory fields and forcing you to fill them in.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/equella/Equella/issues/406>, or mute the thread

**Comment by doolse** [comment]
I found the change here:

```
commit 9a8b1dd8430c9c4ff9762131014764560c728cb4
Author: VARAMAS <ashokkumar.aramasamy@pearson.com>
Date:   Thu Aug 18 18:50:12 2016 +0530

    EQ-1502, EQ-2393, EQ-2197, EQ-1734, EQ-1672, EQ-2752, EQ-2750, EQ-648, EQ-2676, EQ-1238, 
EQ-2755, EQ-2292 - Shadow & Share + assigned tasks

Source/Plugins/Server/com.tle.web.wizard/src/com/tle/web/wizard/section/PagesSection.java

```

The change isn't in the old Pearson master, so i don't know if this is the code change you're talking about?

The reason this came up is because UOW are depending on it working that way but it doesn't really make sense to have mandatory fields that you haven't filled in either, so I'm open to re-fixing it (the previous fix wasn't quite right either)

**Comment by abidingotter** [comment]
I had a feeling it would break something :)  
You shouldn't be able to submit without filling in all mandatory fields, so there would be probably have to be (yet another) option to be able to submit incomplete wizards...
I think the issue was EQ-648 but I don't have access to Pearson Jira anymore. I think the TDC simply merged Peng's branch for the fix.
