### ISSUE TITLE
Couldn't able to build the installer from build.sbt 

### ISSUE THREAD

**Issue by kapil-bunni** [openequella/openEQUELLA#4462]
I'm trying to build the installer from build.sbt under the folder installer. But, getting errors.

**To Reproduce**
To reproduce try to run command sbt run under the path "\openEQUELLA\installer"

**Expected behavior**
This should build an installer.zip through which we can run the application.

**Stacktrace**
PS C:\Program Files (x86)\sbt\bin\openEQUELLA\installer> sbt package
[info] welcome to sbt 1.7.3 (Oracle Corporation Java 1.8.0_202)
[info] loading settings for project installer-build from assembly.sbt ...
[info] loading project definition from C:\Program Files (x86)\sbt\bin\openEQUELLA\Installer\project
C:\Program Files (x86)\sbt\bin\openEQUELLA\Installer\build.sbt:40: error: not found: value installerZip
installerZip := {
^
C:\Program Files (x86)\sbt\bin\openEQUELLA\Installer\build.sbt:53: error: type mismatch;
 found   : Seq[(Comparable[_ >: String with java.io.File <: java.io.Serializable] with java.io.Serializable, String)]
 required: Traversable[(java.io.File, String)]
  IO.zip(allFiles.map(t => (t._1, s"equella-installer-2022.1.0/${t._2}")),
                     ^
[error] Type error in expression
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
**Platform:**
cloned the code from openequella repo
- Using VScode

**Comment by edalex-ian** [comment]
Hey there @kapil-bunni 

I'd suggest you have a look at CONTRIBUTING.md as it covers details around building.

But a few things to note:

1. We don't really support the Windows based build - as we all pretty well build on linux - however it can be done (in theory);
2. Your version of SBT might be too new - not we normally use the SBT wrapper in `./sbt` and that's currently at about 1.5.3; and
3. Lastly, if you want an installer you typically do that from the root of the repository simply with `./sbt installerZip` - but note the use of the wrapper so you might just want to try `sbt installerZip` and if your SBT is correct you might be fine.

Let us know how you get on.

**Comment by edalex-ian** [comment]
Hey @averyirin 

Thanks for the detailed run through. I'll have a closer look for you. In the meantime, don't forget you can always use the CI build for reference as it also essentially sets up a docker image and then builds in it.

https://github.com/openequella/openEQUELLA/blob/develop/.github/workflows/ci.yaml

**Comment by edalex-ian** [comment]
I've figured out the issue you're encountering @averyirin . It's due to attempting to build from a download of the release source rather than from a `git clone`.

The error you thought was related to `application.conf` was actually pointing to line 133 of `build.conf`: https://github.com/openequella/openEQUELLA/blob/2022.2.0/build.sbt#L133

You can see on this line the build is attempting to determine the git hash to include in the build version. You have two options:

1. (Recommended) Build from a clone and simply checkout the tag for the version you want; or
2. (**Not** recommended) Stick with the source archive method, but modify `build.sbt`  so that lines 133-135 are simply replaced with `val shortCommit = "g1234567"` (or a string of your liking) - but this could mess with things when upgrading etc.

Let us know how you get on.

(BTW. You're docker setup is correct - I validated it - you just need to address the above. Be aware there is an - unmaintained - Dockerfile for a build image at https://github.com/openequella/openEQUELLA/blob/develop/docker/docker-build/Dockerfile)

**Comment by kapil-bunni** [comment]
fixed : able to build installer
