### ISSUE TITLE
Integration with Azure Active Directory (Open ID Connect)

### ISSUE THREAD

**Issue by robertwood62** [openequella/openEQUELLA#4720]
Is there a plan to integrate OpenEquella with external identity providers such as Azure Active Directory and/or other Open ID Connect Identity providers?  LDAP based ingestion is a challenge for cloud-based deployments as LDAP is seen as a legacy integration method.  Ideally, we'd be able to 'disable' the default Identity Provider in OpenEquella in favor or using an external enterprise IDP.

**Comment by edalex-ian** [comment]
Hi @robertwood62 ,

Edalex has been having discussions around adding OAuth2/OIDC support to openEQUELLA, and we're hoping to work on it in the not too distant future. However we haven't locked in any dates at this point as we've been focusing on a few other priorities - e.g. LTI 1.3 support.

Although not the same (nor the same level of functionality) openEQUELLA does offer integrations with CAS and organisations have also integrated with Shibboleth to provide SSO capabilities. Obviously both of these platforms also provide OAuth2/OIDC support modules, so that may be something to look into as an interim solution.
