### ISSUE TITLE
Theme editor: uploaded icons are always converted to png files

### ISSUE THREAD

**Issue by mrblippy** [openequella/openEQUELLA#813]
**Describe the bug**
Currently any images uploaded in the logo area of the theme settings page are converted to be png files. Ideally we should be preserving the original file extension.

**To Reproduce**

1. Navigate to the theme settings page
2. In the Logo Settings section click the browse button
3. Upload a the attached gif![dancing](https://user-images.githubusercontent.com/4625498/55527161-8591ca80-56e3-11e9-8865-ca7c3bc5b7f2.gif)
4. Click the apply button
5. WHen you inspect the image that got uploaded to the top left hand side of the screen you will see it's not a png file

**Expected behavior**
Uploaded images should preserve their original file extension 

**Platform:**

- OpenEquella Version: 2018.2, 2019.1

**Comment by SammyIsConfused** [comment]
The conversion to PNG here was done in order to resize the image to the same dimensions as the default openEQUELLA logo, as well as to preserve transparency if it exists. Handling animation in .gifs was not part of the scope when this was implemented, and as such maintaining file type wasn't seen as a priority. Note also, the string displayed in the logo editor that reads "Use a PNG file of 230x36 pixels for best results.".
